"""Name Sheet."""
from adhocracy.interfaces import (
    ISheet,
    IISheet,
    IResourcePropertySheet,
)
from adhocracy.sheets import ResourcePropertySheetAdapter
from adhocracy.schema import Identifier
from zope.interface import (
    provider,
    taggedValue,
)
from zope.interface.interfaces import IInterface

import colander


@provider(IISheet)
class IName(ISheet):

    """Human readable resource Identifier, used to build object paths."""

    taggedValue('schema', 'adhocracy.sheets.name.NameSchema')


class NameSchema(colander.Schema):

    """Colander schema for IName."""

    name = Identifier(default='', missing=colander.drop)


@provider(IISheet)
class INameReadOnly(IName):

    """Same as IName but name is autogenerated."""

    taggedValue('schema', 'adhocracy.sheets.name.NameReadOnlySchema')


class NameReadOnlySchema(colander.Schema):

    """Colander schema for INameReadOnly."""

    name = Identifier(readonly=True, default='', missing=colander.drop)


def includeme(config):
    """Register adapter."""
    config.registry.registerAdapter(ResourcePropertySheetAdapter,
                                    (IName, IInterface),
                                    IResourcePropertySheet)

    config.registry.registerAdapter(ResourcePropertySheetAdapter,
                                    (INameReadOnly, IInterface),
                                    IResourcePropertySheet)
