#!/bin/bash

function modulePath() {
    echo $1 | sed 's/.ts$//'
}

function moduleName() {
    echo "T$1"
}

echo '/**'
echo ' * AUTO-GENERATED BY ./AdhocracyIg.sh.  DO NOT EDIT.'
echo ' *'
echo ' * This module imports and registers all frontend integration tests.'
echo ' * Only works in browser with backend running.  Visit `igtest.html`.'
echo ' */'
echo

export count=1
for i in `find . -name '*Ig.ts' | grep -v ./AdhocracyIg.ts | sort`; do
    echo "import "`moduleName $count`" = require(\""`modulePath $i`"\");"
    count=$[$count+1]
done

echo

echo "jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000;"
echo

count=1
for i in `find . -name '*Ig.ts' | grep -v ./AdhocracyIg.ts`; do
    echo `moduleName $count`".register();"
    count=$[$count+1]
done
