#!/bin/bash

function modulePath() {
    echo $1 | sed 's/.ts$//'
}

function moduleName() {
    echo "T$1"
}

echo '/**'
echo ' * AUTO-GENERATED BY ./AdhocracyIg.sh.  DO NOT EDIT.'
echo ' *'
echo ' * This module imports and registers all frontend integration tests.'
echo ' * Only works in browser with backend running.  See `igtest.html`.'
echo ' *'
echo ' * Ig tests aim at something between selenium/splinter/protactor-style'
echo ' * end-to-end testing and pure jasmine unit tests.  It lets you start'
echo ' * a service like AdhHttp, talk to the backend, and examine the'
echo ' * result.  In order to achieve this, the angular dependency is'
echo ' * passed to every registration function as an argument.'
echo ' */'
echo

export count=1
for i in `find . -name '*Ig.ts' | grep -v ./AdhocracyIg.ts | sort`; do
    echo "import "`moduleName $count`" = require(\""`modulePath $i`"\");"
    count=$[$count+1]
done

echo

echo "jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000;"
echo

echo "export var register = (angular) => {"
count=1
for i in `find . -name '*Ig.ts' | grep -v ./AdhocracyIg.ts`; do
    echo "    `moduleName $count`.register(angular);"
    count=$[$count+1]
done
echo "};"
