# requirement:
# nmp install -g typescript
# more info on tsc at http://www.typescriptlang.org/

compile:
	tsc --module amd --sourcemap --out Adhocracy.js Adhocracy.ts

clean:
	find . -name '*~' -exec rm {} \;
	find . -name '*.js' -exec rm {} \;
	find . -name '*.js.map' -exec rm {} \;
