#!/bin/bash

function modulePath() {
    echo $1 | sed 's/.ts$//'
}

function moduleName() {
    echo "T$1"
}

echo '/**'
echo ' * AUTO-GENERATED BY ./AdhocracySpec.sh.  DO NOT EDIT.'
echo ' *'
echo ' * This module imports and registers all frontend unit tests.'
echo ' */'
echo

export count=1
for i in `find . -name '*Spec.ts' | grep -v ./AdhocracySpec.ts | sort`; do
    echo "import "`moduleName $count`" = require(\""`modulePath $i`"\");"
    count=$[$count+1]
done

echo

echo "jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000;"
echo

count=1
for i in `find . -name '*Spec.ts' | grep -v ./AdhocracySpec.ts`; do
    echo `moduleName $count`".register();"
    count=$[$count+1]
done
