#!/bin/sh
if [ "$ADHOCRACY_GIT_NO_VERIFY" != "1" ]; then
echo -n "\n\nCode validation pre commit hook: bin/check_code\n"
echo -n "To disable, run 'git commit' with '--no-verify' or "
echo -n "set shell variable ADHOCRACY_GIT_NO_VERIFY to \"1\".\n\n\n"
exec bin/check_code
else
echo "\n\nGit pre-commit hook disabled by ADHOCRACY_GIT_NO_VERIFY\n\n"
fi