from zope.interface import (
    Interface,
    taggedValue,
)
from substanced.interfaces import (
    IFolder,
    IAutoNamingFolder
)


# Basic adhocracy content

class IContent(Interface):
    """Marker interface for adhocracy content objects
    """

    # TODO
    #  A tagged value "add_permission" sets the permission
    #  to create this content object and add it to the object hierarchy.
    # (in addition to the "addable_content_interfaces"  settings)
    # taggedValue("add_permission", "add-content")

    # A perm permission to list folder contents, view content meta data, search
    # taggedValue("view_permission", "view-content")


class IContentItem(IContent):
    """Marker interface for adhocracy content objects
    """


class IContentFolder(IContent, IFolder):
    """Marker interface for adhocracy content objects
    """


# Basic Pools

class IPool(IContentFolder):
    """Folder to define a namespace for supergraph nodes
       and to provide services like catalog, workflow registry, ...
   """
    # content type registry parameters
    # modifiable name TODO
    taggedValue("content_name", "Pool")
    # addable content types, class heritage is honored
    taggedValue("addable_content_interfaces",
                ["adhocracy.contents.interfaces.IPool"])
    # make this addable if supertype is addable
    taggedValue("is_implicit_addable", True)  # default True
    # object factory parameters
    taggedValue("propertysheet_interfaces", ["adhocracy.propertysheets.interfaces.IName"])
    taggedValue("content_class", "substanced.folder.Folder")  # required
    # autogenerated
    # IPool.__identifier__  # substanced content type id
    #taggedValue("add_view", 'add_adhocracy.contents.interfaces.IPool') # add view for substanced sdi,


class INodeContainer(IPool):
    """Pool for all versions and tags of one node versions darc
       or other node containers that are part of the essence.

       Children:

           _versions = INodeVersions object

           _tags = INodeTags object

       A tagged value "node_content_type" to set the type of node
       addable to this container.
    """
    # content type registry parameters
    taggedValue("content_name", "NodeContainer")  # modifiable name TODO
    taggedValue("addable_content_interfaces",
                ["adhocracy.contents.interfaces.INodeContainer"])
    # object factory parametersd
    taggedValue("content_class", "adhocracy.contents.NodeContainerFolder")  # required
    taggedValue("propertysheet_interfaces", ["adhocracy.propertysheets.interfaces.IName"])
    taggedValue("node_content_type", "adhocracy.contents.interfaces.INode")  # required


class INodeVersions(IPool, IAutoNamingFolder):
    """Pool to store all node versions
    """
    taggedValue("is_implicit_addable", False)
    taggedValue("addable_content_interfaces",
                ["adhocracy.contents.interfaces.INode"])
    taggedValue("content_class", "substanced.folder.RandomAutoNamingFolder")


class INodeTags(IPool):
    """Pool to store tag nodes to reference specific node versions
    """
    taggedValue("is_implicit_addable", False)
    taggedValue("addable_content_interfaces",
                ["adhocracy.contents.interfaces.INode"])
    taggedValue("content_class", "substanced.folder.Folder")


# Basic Node

class INode(IContentItem):
    """Marker interface representing a supergraph node"""
    taggedValue("content_class", "substanced.folder.Folder")  # this should be a simple object instead
    taggedValue("propertysheet_interfaces", ["adhocracy.propertysheets.interfaces.INameReadonly",
                                             "adhocracy.propertysheets.interfaces.IVersionable"])

# Concrete Nodes


class IProposal(INode):
    """Proposal node"""
    taggedValue("content_class", "substanced.folder.Folder")
    taggedValue("propertysheet_interfaces", ["adhocracy.propertysheets.interfaces.INameReadonly",
                                             "adhocracy.propertysheets.interfaces.IDocument",
                                             "adhocracy.propertysheets.interfaces.IVersionable"])


class IProposalContainer(INodeContainer):
    """Proposal node container"""
    taggedValue("addable_content_interfaces", ["adhocracy.contents.interfaces.IProposalContainer"])
    taggedValue("node_content_type", "adhocracy.contents.interfaces.IProposal")
    taggedValue("content_class", "adhocracy.contents.NodeContainerFolder")
    taggedValue("propertysheet_interfaces", ["adhocracy.propertysheets.interfaces.IName"]),


class IParagraph(INode):
    """Paragraph of documents"""
    taggedValue("content_class", "substanced.folder.Folder")
    taggedValue("propertysheet_interfaces", ["adhocracy.propertysheets.interfaces.INameReadonly",
                                             "adhocracy.propertysheets.interfaces.IText",
                                             "adhocracy.propertysheets.interfaces.IVersionable"])


class IParagraphContainer(INodeContainer):
    """IParagraph DAG"""
    taggedValue("addable_content_interfaces", ["adhocracy.contents.interfaces.IParagraphContainer"])
    taggedValue("node_content_type", "adhocracy.contents.interfaces.IParagraph")
    taggedValue("content_class", "adhocracy.contents.NodeContainerFolder")
    taggedValue("propertysheet_interfaces", ["adhocracy.propertysheets.interfaces.IName"]),
