"""Shared acceptance test functions."""
from random import choice
from time import sleep
import requests
import json

from splinter.driver.webdriver import WebDriverElement

from adhocracy_core.testing import god_login
from adhocracy_core.testing import god_password
from adhocracy_core.testing import annotator_password
from adhocracy_core.testing import annotator_login
from selenium.common.exceptions import NoSuchElementException


# FIXME: root_uri must be constructed from etc/*.ini, not hard-coded here!
root_uri = 'http://localhost:6542'
verbose = False

ALPHABET = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789'
WHITESPACE = ' '


def get_random_string(n=10, whitespace=False) -> str:
    """Return autogenerated string."""
    alphabet = ALPHABET + WHITESPACE if whitespace else ALPHABET
    return ''.join(choice(alphabet) for i in range(n))


def wait(condition, step=0.1, max_steps=10) -> bool:
    """Wait for a condition to become true."""
    for i in range(max_steps - 1):
        try:
            result = condition()
            if hasattr(result, 'visible'):
                if result.visible:
                    return True
                else:
                    sleep(step)
            else:
                if result:
                    return True
                else:
                    sleep(step)
        except ValueError:
            pass
        except NoSuchElementException:
            pass
    return condition()


def login(browser, name_or_email, password,
          expect_success=True,
          visit_root=True):
    """Login user with name and password."""
    if is_logged_in(browser):
        return
    login_url = browser.app_url + 'login'
    browser.visit(login_url)
    fill_input(browser, '.login [name="nameOrEmail"]', name_or_email)
    fill_input(browser, '.login [name="password"]', password)
    click_button(browser, '.login [type="submit"]')
    if expect_success and not browser.wait_for_condition(is_logged_in, 20):
        raise Exception('login failed.')
    if visit_root:
        browser.visit(browser.root_url)


def login_god(browser, **kwargs):
    """Login god user."""
    login(browser, god_login, god_password, **kwargs)


def login_annotator(browser, **kwargs):
    """Login annotator user."""
    login(browser, annotator_login, annotator_password, **kwargs)


def logout(browser):
    """Logout user."""
    if is_logged_in(browser):
        click_button(browser, '.user-indicator-logout')
        browser.wait_for_condition(is_logged_out, 30)


def is_logged_in(browser):
    """Check if user is logged in."""
    return browser.is_element_present_by_css('.user-indicator-logout')


def is_logged_out(browser):
    """Check if user is logged out."""
    return browser.is_element_not_present_by_css(
        '.user-indicator-logout')


def fill_input(browser, css_selector, value):
    """Find `css_selector` and fill value."""
    element = browser.find_by_css(css_selector).first
    element.fill(value)


def click_button(browser, css_selector):
    """Find `css_selector` and click."""
    element = browser.find_by_css(css_selector).first
    element.click()


def title_is_in_listing(listing, title: str) -> bool:
    """Check that a listing element with text == `title` exists."""
    for element in listing.find_by_css('.listing-element'):
        wait(lambda: element.text, max_steps=5)
        if element.text == title:
            return True


def get_listing_create_form(listing) -> WebDriverElement:
    """Open and return the create form of a listing."""
    return listing.find_by_css('.listing-create-form').first


def get_column_listing(browser, column_name: str) -> WebDriverElement:
    """Return the listing in the content column ."""
    column = browser.find_by_css('.moving-column-' + column_name)
    listing = column.first.find_by_css('.listing')
    return listing


def get_list_element(listing, text, descendant=None, max_steps=20):
    """Return list element with text == `text`."""
    for element in listing.find_by_css('.listing-element'):
        wait(lambda: element.text, max_steps=max_steps)
        if descendant is None:
            element_text = element.text
        else:
            element_text = element.find_by_css(descendant).first.text
        if element_text == text:
            return element


def api_login(name_or_email: str, password: str) -> dict:
    """Login user and return user token and path."""
    uri = root_uri + '/login_username'
    headers = {
        'Content-Type': 'application/json;charset=UTF-8',
        'Accept': 'application/json, text/plain, */*',
        'Accept-Encoding': 'gzip,deflate',
        'Connection': 'keep-alive',
        'Accept-Language': 'en-US,en;q=0.8',
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
        'Content-Length': '36'
    }
    body = json.dumps({
        'name': name_or_email,
        'password': password
    })
    response = requests.post(uri, headers=headers, data=body)
    if verbose:
        print('\n')
        print(uri)
        print(headers)
        print(body)
        print(response)
        print(response.text)
    assert response.status_code == 200

    data = response.json()
    assert data['status'] == 'success'

    return {'user_token': data['user_token'],
            'user_path': data['user_path']}


def api_login_god() -> dict:
    """Login in as god and return user token and path."""
    return api_login(god_login, god_password)
