from zope.interface import (
    Interface,
    taggedValue,
)

# Basic adhocracy content


class IContent(Interface):

    """Marker interface for adhocracy content objects"""

    #  A tagged value "add_permission" sets the permission
    #  to create this content object and add it to the object hierarchy.
    taggedValue("permission_add", "add")
    # A perm permission to list folder contents, view content meta data, search
    taggedValue("permission_view", "view")
    # make this addable if supertype is addable
    taggedValue("is_implicit_addable", True)
    # extended propertysheets
    taggedValue("extended_propertysheet_interfaces",
                set())  # subtypes should override this
    # autogenerated in __init__.includeme:
    # IPool.__identifier__  # substanced content type id
    # taggedValue("add_view", 'add_adhocracy.resources.interfaces.IPool') # add
    # view for substanced sdi,

# Basic Pools


class IPool(IContent):

    """Folder content in the object hierachy, namespace for Fubels,
       structure and configure child fusels for a specic Beteiligungsverfahren.
       "A tagged value "addable_content_interfaces" to set addable content types"
    """
    # modifiable name FIXME
    taggedValue("content_name", "Pool")  # subtypes should overide this
    # python class
    taggedValue("content_class", "substanced.folder.Folder")
    # propert asdf object factory parameters
    taggedValue("basic_propertysheet_interfaces",
                set(["adhocracy.properties.interfaces.IName",
                     "adhocracy.properties.interfaces.IPool"]))
    # addable content types, class heritage is honored
    taggedValue("addable_content_interfaces",  # subtypes should override this
                set(["adhocracy.resources.interfaces.IPool"]))


class IFubelVersionsPool(IPool):

    """Pool for all Fubel versions (DAG), tags and related Pools.

       A tagged value "fubel_content_type" to set the type of VersionableFubel
       addable to this container.
    """
    taggedValue("content_name", "FubelVersionsPool")
                # subtypes should overide this
    taggedValue("addable_content_interfaces", set([
                # subtypes have to overide this
                "adhocracy.resources.interfaces.IVersionableFubel",
                # == fubel_content_type!!!
                "adhocracy.resources.interfaces.ITag",
                ]))
    taggedValue("fubel_content_type",  # subtypes have to overide this
                "adhocracy.resources.interfaces.IVersionableFubel")
    taggedValue("basic_propertysheet_interfaces", set(
                ["adhocracy.properties.interfaces.IName",
                 "adhocracy.properties.interfaces.ITags",
                 "adhocracy.properties.interfaces.IVersions",
                 "adhocracy.properties.interfaces.IPool"]))


# Basic Fubels

class IFubel(IContent):

    """Non Versionable Fubel."""
    taggedValue("content_class", "persistent.Persistent")
    taggedValue("content_name", "Fubel")  # subtypes should overide this
    taggedValue("basic_propertysheet_interfaces", set(
                ["adhocracy.properties.interfaces.IName"]))


class IVersionableFubel(IFubel):

    """ Versionable Fuble, little item content created during a
        Beteiligungsverfahren (mainly).

    """
    taggedValue("content_name", "VersionableFubel")
                # subtypes should overide this
    taggedValue("basic_propertysheet_interfaces", set(
                ["adhocracy.properties.interfaces.INameReadonly",
                 "adhocracy.properties.interfaces.IVersionable"]))


# Concrete Fubels and FubelVersionsPools

class IProposal(IVersionableFubel):

    """Proposal Fubel"""
    taggedValue("extended_propertysheet_interfaces", set(
                ["adhocracy.properties.interfaces.IDocument"]))


class IProposalVersionsPool(IFubelVersionsPool):

    """Proposal Versions Pool"""
    taggedValue("addable_content_interfaces", set(
        ["adhocracy.resources.interfaces.ITags",
         "adhocracy.resources.interfaces.IFubelVersionsPool"]))
    taggedValue("fubel_content_type",
                "adhocracy.resources.interfaces.IProposal")


class ISection(IVersionableFubel):

    """Paragraph of documents"""


class ISectionVersionsPool(IFubelVersionsPool):

    """Paragraph Versions Pool"""
    taggedValue("addable_content_interfaces", set(
        ["adhocracy.resources.interfaces.ITags",
         "adhocracy.resources.interfaces.ISection"]))
    taggedValue("fubel_content_type", "adhocracy.resources.interfaces.ISection")
