"""Interfaces for adhocarcy resources."""
from zope.interface import (
    Interface,
    taggedValue,
)
from substanced.interfaces import IAutoNamingFolder
from substanced.interfaces import IFolder


class IResource(Interface):

    """Marker interface with tagged values to configure a resource type."""

    taggedValue("content_name", "")
    """Human readable name, subtypes have to override"""
    taggedValue("content_class", "persistent.mapping.PersistentMapping")
    """Class to create content objects"""

    taggedValue("permission_add", "add")
    """Permission to add this content object to the object hierarchy. """
    taggedValue("permission_view", "view")
    """Permission to view content data and view in listings"""
    taggedValue("is_implicit_addable", True)
    """Make this content type adddable if supertype is addable."""

    taggedValue("basic_properties_interfaces", set())
    """Basic property interfaces to define data """
    taggedValue("extended_properties_interfaces", set())
    """Extended property interfaces to define data, subtypes should override"""
    # autogenerated in __init__.includeme:
    # IPool.__identifier__  # substanced content type id
    # taggedValue("add_view", 'add_adhocracy.resources.interfaces.IPool') # add
    # view for substanced sdi,


class IPool(IResource, IFolder):

    """Folder in the object hierarchy.

    Namespace, structure and configure Fubels for a Participation Process.
    Additional TaggedValue: "addable_content_interfaces"

    """

    taggedValue("content_class", "substanced.folder.Folder")
    taggedValue("basic_properties_interfaces",
                set(["adhocracy.properties.interfaces.IName",
                     "adhocracy.properties.interfaces.IPool"]))
    taggedValue("addable_content_interfaces",
                set(["adhocracy.resources.interfaces.IPool"]))
    """ Set addable content types, class heritage is honored"""


class IFubelVersionsPool(IPool, IAutoNamingFolder):

    """Pool for all VersionableFubels (DAG), tags and related Pools.

    Additional TaggedValue: "fubel_type"

    """

    taggedValue("content_class",
                "substanced.folder.SequentialAutoNamingFolder")
    taggedValue("content_name", "FubelVersionsPool")
    taggedValue("basic_properties_interfaces", set(
                ["adhocracy.properties.interfaces.IName",
                 "adhocracy.properties.interfaces.ITags",
                 "adhocracy.properties.interfaces.IVersions",
                 "adhocracy.properties.interfaces.IPool"]))
    taggedValue("addable_content_interfaces", set([
                "adhocracy.resources.interfaces.IVersionableFubel",
                "adhocracy.resources.interfaces.ITag",
                ]))
    taggedValue("fubel_type",
                "adhocracy.resources.interfaces.IVersionableFubel")
    """Type of VersionableFubel for this VersionPool.
    Subtypes have to override.
    """


class IFubel(IResource):

    """Small object without versions and children."""

    taggedValue("content_name", "Fubel")
    taggedValue("basic_properties_interfaces", set(
                ["adhocracy.properties.interfaces.IName"]))


class IVersionableFubel(IFubel):

    """Versionable Fuble, created during a Participation Process (mainly)."""

    taggedValue("content_name", "VersionableFubel")
    taggedValue("basic_properties_interfaces", set(
                ["adhocracy.properties.interfaces.INameReadOnly",
                 "adhocracy.properties.interfaces.IVersionable"]))

# # Concrete Fubels and FubelVersionsPools
#
# class IProposal(IVersionableFubel):
#
#     """Proposal Fubel"""
#     taggedValue("extended_properties_interfaces", set(
#                 ["adhocracy.properties.interfaces.IDocument"]))
#
#
# class IProposalVersionsPool(IFubelVersionsPool):
#
#     """Proposal Versions Pool"""
#     taggedValue("addable_content_interfaces", set(
#         ["adhocracy.resources.interfaces.ITags",
#          "adhocracy.resources.interfaces.IFubelVersionsPool"]))
#     taggedValue("fubel_content_type",
#                 "adhocracy.resources.interfaces.IProposal")
#
#
# class ISection(IVersionableFubel):
#
#     """Paragraph of documents"""
#
#
# class ISectionVersionsPool(IFubelVersionsPool):
#
#     """Paragraph Versions Pool"""
#     taggedValue("addable_content_interfaces", set(
#         ["adhocracy.resources.interfaces.ITags",
#          "adhocracy.resources.interfaces.ISection"]))
#     taggedValue("fubel_type", "adhocracy.resources.interfaces.ISection")
